language: groovy
jdk:
  - openjdk8
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- ./gradlew clean && ./gradlew war
deploy:
  provider: releases
  api_key:
    secure: 0QQyZN/FB7BbN4H66zY23SrpXORGACwErY/1WAvuVGPcXw8wwO2vyUUMLMj1bGdAyEu8OZnOyFmIOOZiLPTj7mbaV3rW0YvRtmiLZnnU2WNTtlcg+AQzhDlYtfZ8EBbsRxlQTOQF+QWst/SY9CR1/1uf8EvZeWAOfHtY3vNc0a1yn1z6U8HXdxOa9lfa1slppYDP/4o3AP16u3gIXeLL+oqnz0xpJMa9DYm8rDr7ZmkTXJvCDLPUMrtqwUBpLXu8wibsFzpRgcOvI94mEoEUCEFO7il80NCMygSKb2vfMfo6QNgdzoUsiUo7pS3NmEv62+pzfPiiPxsKx8jTm0dBxl19q65tHfWlEBtinkCoC648TjBvyWKcRJCt0lxttn0LoB6nN4AyM7kXkRyThopoTSv0RGa6rkzWGQBypbuvTCeBfrCAACbX4eNsrbCsvnWsNFUvwUHI8wCN6YnS+AiadmwBAr5BFrbqrzSg2+lugSswJ5AWVLd3Tp54AjP9uC7DyawZ1mjG4z+YKd1lAu+0vxChOcDAUPjvYrVtToj/TcaAQZKpdCpGJhvG5ttIEAXuUKcEr0dwqaydA+9QLzDT9qeo4yETkTlG4KZCwrG87ayhP/XdaQMTpCHEOrKeo/ibAmRTXm4FhRmVwQw6TAi/lhIkPcgnp4KVSfQ7vHtHgZI=
  file_glob: true
  file: build/libs/ala-bie-*.war
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/ala-bie
    all-branches: true
